version: '3'

services: 
    db:
        build: ./Db
    app:
        build: 
            context: .
            dockerfile: StoreManager/Dockerfile
        ports: 
            - 8080:80
        depends_on: 
            - db